[package]
name = "cfg_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pci-cfg-rs = { version = "0.1.2", git = "https://github.com/ekknod/pci-cfg-rs.git" }